module.exports = {
  // NIS & Government forms
  'Application for a Permit to Remove a Building/House or Boat': 'VEP',
  'Claim for Unemployment Benefit': 'UB',
  'NIS Online Social Security Service Registration Form': 'OSS',
  'Declaration by Pensioners 60 Years and Over': 'PD',
  'National Insurance Contributions Certificate': 'DP10',
  'Direct Deposit Form': 'DD',
  'Self-Employment Registration': 'SE',
  'Contributions Payment Certificate — Self-employed Persons': 'SECP',
  'Termination of Services / Layoff Certificate': 'TC',

  // Barbados Licensing Authority (BLA) forms
  'Change of Engine': 'COE',
  'Change of Use of Vehicle': 'COU',
  'Request to Change the Colour of Vehicle': 'CVC',
  'Declaration Form – Company Vehicle Registration for Private Use': 'DC',
  'Declaration Form – Partnership Vehicle Registration for Private Use': 'DP',
  'Declaration Form – Sole Trader Vehicle Registration for Private Use': 'DST',
  'Request for Duty Free Concession (Business)': 'DFB',
  'Request for Duty Free Concession (Individual)': 'DFI',
  'Application for the Importation of Vehicles into Barbados': 'IOV',
  'Apply for a Motor Vehicle Inspection': 'LA',
  'Odometer Reading Validation': 'OR',
  'Register Your Vehicle for a Temporary Stay in Barbados': 'RTS',
  'Request for Graphics and/or Lettering on Vehicle': 'RFG',
  'Retain Your Vehicle Registration Number': 'RON',
  'Sale of Vehicle (Individual Owner)': 'SVI',
  'Sale of Vehicle (Joint Owners)': 'SVJ',
  'Scrap or Sell Vehicle in Parts': 'SOV',
  'Transfer of Vehicle (Individual Owner)': 'TVI',
  'Transfer of Vehicle (Joint Owners)': 'TVJ',
  'Application for an Approved Vanity Plate': 'VP',
  'Application for Vehicle Investigation': 'VI',
  'Register or Renew Your Motor Vehicle Licence': 'VRR',
};
