module.exports = {
  // NIS & Government forms
  'Application for a Permit to Remove a Building/House or Boat': 'VEP',
  'Claim for Unemployment Benefit': 'UB',
  'NIS Online Social Security Service Registration Form': 'OSS',
  'Declaration by Pensioners 60 Years and Over': 'PD',
  'National Insurance Contributions Certificate': 'DP10',
  'Direct Deposit Form': 'DD',
  'Self-Employment Registration': 'SE',
  'Contributions Payment Certificate — Self-employed Persons': 'SECP',
  'Termination of Services / Layoff Certificate': 'TC',

  // Barbados Licensing Authority (BLA) forms
  'Change of Engine': 'COE',
  'Change of Use of Vehicle': 'COU',
  'Request to Change the Colour of Vehicle': 'CVC',
  'Declaration Form – Company Vehicle Registration for Private Use': 'DC',
  'Declaration Form – Partnership Vehicle Registration for Private Use': 'DP',
  'Declaration Form – Sole Trader Vehicle Registration for Private Use': 'DST',
  'Request for Duty Free Concession (Business)': 'DFB',
  'Request for Duty Free Concession (Individual)': 'DFI',
  'Application for the Importation of Vehicles into Barbados': 'IOV',
  'Apply for a Motor Vehicle Inspection': 'LA',
  'Odometer Reading Validation': 'OR',
  'Register Your Vehicle for a Temporary Stay in Barbados': 'RTS',
  'Request for Graphics and/or Lettering on Vehicle': 'RFG',
  'Retain Your Vehicle Registration Number': 'RON',
  'Sale of Vehicle (Individual Owner)': 'SVI',
  'Sale of Vehicle (Joint Owners)': 'SVJ',
  'Scrap or Sell Vehicle in Parts': 'SOV',
  'Transfer of Vehicle (Individual Owner)': 'TVI',
  'Transfer of Vehicle (Joint Owners)': 'TVJ',
  'Application for an Approved Vanity Plate': 'VP',
  'Application for Vehicle Investigation': 'VI',
  'Register or Renew Your Motor Vehicle Licence': 'VRR',
  'Change of Address': 'COA',
  'Report a Stolen Vehicle': 'SV',
  'Change Your Driving Exam Date': 'DEC',
  'Replace a Lost Learner Permit': 'LLP',
  'Change Your Driving Test Date': 'CDT',
  'Change Your Regulation Test Date': 'CRT',
  'Request for a Driving Record': 'DR',
  'Request for Duplicate PSV Driving Licence': 'DPSV',
  'Apply for a New Learner Permit': 'NLP',
  'Apply to Tint Your Vehicle Windows': 'TV',
  'Request for Reinstatement of Driving Licence': 'RDL',
  'Transfer an International Driving Licence': 'TIL',
  'Apply for a Disabled Parking Permit': 'DPP',
  'Book a Regulation Test Appointment': 'RTA',
  'Register a Bicycle or Motorcycle': 'RBM',
  'Transfer of Vehicle Due to Death of Owner': 'TVD',
  'MO Plate Renewal': 'MO',
  "Apply for a Driver's Licence": 'DL',
  "Apply for a Conductor's Licence": 'CL',
  "Conductor's Licence": 'CL',
  'Apply for a Taxi Driver Licence': 'TDL',
  'Taxi Driver Licence': 'TDL',
  'Apply for an International Driving Permit': 'IDP',
  'International Driving Permit': 'IDP',
  'Apply for an F-Class Driving Licence': 'FCL',
  'F-Class Driving Licence': 'FCL',
  'Register a Private Vehicle': 'VRP',
  'Vehicle Registration (Private Vehicle)': 'VRP',
  'Apply for Tinted Window Exemption (Businesses)': 'TWE',
  'Application for Tinted Window Exemption (Businesses)': 'TWE',
  'Apply to Be an Approved Vehicle Garage': 'AVG',
  'Application to Be an Approved Vehicle Garage': 'AVG',
  'Apply for Approval as a Number Plate Manufacturer': 'NPM',
  'Apply for a Duty Free Vehicle Concession': 'DFV',
  'Apply for Limited Trade Plates': 'LTP',
  'Apply for an Oral Test for a Taxi Licence': 'TOT',

  // CAIPO (Corporate Affairs and Intellectual Property Office) forms
  'Articles of Reincorporation': 'ARI',
  'Registration of a Business Name (Form I)': 'BN',
  'CARICOM Complaints Form': 'CC',
  'Company Name Search and Reservation (Form 33)': 'CNS',
  'Declaration of Compliance (Companies Act Cap. 308)': 'DC308',
  'Declaration of Compliance (Non-Profit Company)': 'DCNP',
  'Financial Statements Exemption': 'FSE',
  'Geographical Indications Agent Authorisation': 'GIA',
  'International Business Company Licence Application': 'IBC',
  'Registered Agent Authorisation': 'RA',
  'SRL Name Search and Reservation': 'SRL',
  'Declaration of URL / Domain Name Ownership': 'URL',

  // IMMD (Citizenship, Immigration and Passports) forms
  'CARICOM Indefinite Stay Application': 'CIS',
  'Registration as a Citizen (Adult)': 'RCA',
  'Registration as a Citizen by Marriage (Form R.1)': 'RCM',
  'Registration as a Citizen (Under 18)': 'RCU',
  'Citizenship Affidavit': 'CAF',
  'Certificate of Citizenship by Descent': 'CCD',
  'Commonwealth Citizenship Registration': 'CCR',
  'Immigrant Status and Non-National Registration (Form A)': 'ISA',
  'Permanent Resident Registration (Form A1)': 'PRA',
  'Short Term Work Permit or Training Attachment': 'SWP',
  'Certificate by Non-Immigrant Student (Form H-2)': 'H2',
  'Certificate of Eligibility for Student Status (Form H-1)': 'H1',
  'Work Permit / Extension / Job Offer': 'WP',

  // NAB (National Assistance Board) forms
  'Application for Home Care Services': 'HC',
  "Seniors' Recreational Activities Programme": 'SRA',

  // NIS (additional forms)
  'NIS Educational Status Form': 'ESF',
  'Register as an Employer for NIS Online Services': 'ER',
  'NIS Life Certificate': 'LC',
  'Claim for Old Age Contributory Pension': 'OAP',

  // Royal Barbados Police Force forms
  'Request a Police Accident Report': 'PAR',
  'Apply for a Motorcade Permit': 'MC',
  'Apply for a Loud Music Permit': 'LMP',
  'Apply to Import or Export Firearms': 'IEF',
  'Apply for a Firearm Licence': 'FL',
  'Apply for a Firearms Dealer/Gunsmith Licence': 'FDL',
  'Apply for a Shooting Club Licence': 'SCL',

  // Land Tax Department forms
  'Request a Land Tax Demand Notice': 'LTDN',
  'Request an Advance Land Tax Assessment': 'LTAA',
  'Notice of Change of Ownership (Land Tax)': 'LTCO',

  // Town and Country Planning forms
  'Building Development Application': 'BDA',
  'Permission to Erect a Chattel House': 'CH',
  'Permission to Construct or Alter a Building': 'PCB',

  // Division of Youth Affairs (YDP) forms
  'Get Hired Programme 2026': 'GHP',
  'Youth Achieving Results (Performing Arts)': 'YARPA',
  'Youth Achieving Results (Visual Arts)': 'YARVA',
  'National Community Cultural Training Programme 2025': 'NCCTP',

  // Other government forms
  'Sell Goods or Services on a Beach or Park': 'SBP',
  'Agribusiness Farm Registration': 'AFR',
  'Register a Will': 'WL',
  'Apply for a New Permit': 'NPA',
  'Transfer a Permit': 'TP',
};
